# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'get_latest_by': 'date',
                'permissions': (('view_project', 'Can view project'), ('edit_project', 'Can edit project'), ('edit_server', "Can edit projects's servers"), ('edit_update', "Can edit projects's updates"), ('run_command', "Can run project's commands"), ('add_server', 'Can add server to project'), ('add_update', 'Can add update to project'), ('del_server', "Can delete project's servers"), ('del_update', "Can delete project's updates")),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=200)),
                ('wdir', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=255)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.FileField(upload_to=ups.models.get_upload_to)),
                ('desc', models.TextField(max_length=255)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.Project')),
            ],
        ),
    ]
