# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
            ],
            options={
                'get_latest_by': 'date',
                'permissions': (('view_project', 'Can view project'),),
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=200)),
                ('wdir', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.Project')),
            ],
            options={
                'get_latest_by': 'date',
                'permissions': (('view_server', 'Can view server'),),
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.FileField(upload_to=ups.models.get_upload_to)),
                ('desc', models.TextField(max_length=255)),
                ('slug', models.SlugField(max_length=64)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ups.Project')),
            ],
            options={
                'get_latest_by': 'date',
                'permissions': (('view_update', 'Can view update'),),
            },
        ),
    ]
