# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_auto_20170123_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server',
            new_name='project',
        ),
    ]
